### ISSUE TITLE
Failed to connect to the  AWS IoT

### ISSUE THREAD

**Issue by Jack1314** [aws/aws-iot-device-sdk-arduino-yun#1]
Hi,

I upload the BasicPubSub example to the Arduino Yún board. But it connected failed!
We could see the serial port printed as shown below:
![Uploading failed.png…]()

We also see the python file run.
![Uploading python client.png…]()

And Yesterday evening the connection was successful.
![Uploading success.jpg…]()

Please give the answer to us. Thanks!

**Comment by Jack1314** [comment]
Hi,

I upload the BasicPubSub example to the Arduino Yún board. But it connected failed!
We could see the serial port printed as shown be


We also see the python file run.
![Uploading python client.png…]()


And Yesterday evening the connection was successful.
![Uploading success.jpg…]()

Please give the answer to us. Thanks!

**Comment by Jack1314** [comment]
Hi,

I upload the BasicPubSub example to the Arduino Yún board. But it connected failed!
We could see the serial port printed as shown below:
"
AWS IoT SDK Version(dev) 1.0.0-

Connect failed!
-5
Subscribe failed!
-7
Publish failed!
-6
loop 0 done
Publish failed!
-6
loop 1 done
loop 2 done
loop 3 done
loop 4 done
Publish failed!
"

We also see the python file run.
 1777 root     13232 S    python aws_iot_mqtt_client.py

And Yesterday evening the connection was successful.
"
AWS IoT SDK Version(dev) 1.0.0-

loop 0 done
CALLBACK:
new message 0
loop 1 done
CALLBACK:
new message 1
"

Please give the answer to us. Thanks!

**Comment by Pillar1989** [comment]
I have the same problem, what's wrong with  arduino yun sdk ?

**Comment by amirthar** [comment]
@Jack1314 @Pillar1989 - thank you for trying out the Arduino Yún SDK. Could you please tell us whether you have successfully created and registered your certs with AWS IoT?
Please reference the below and let us know if you run into issues.
http://docs.aws.amazon.com/iot/latest/developerguide/secure-communication.html
https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/README.md

**Comment by Pillar1989** [comment]
Yes, we can use the same certs file on Beaglebone green. it's work fine. so I guess the arduino yun SDK problem

**Comment by Jack1314** [comment]
@amirthar   I used the same  AWS IoT CA file, private key and certificate file with Arduino yun.   The night before the connection to AWS IoT was successful, but it connected failed yesterday.

**Comment by liuszeng** [comment]
Hi @Pillar1989. Thank you for your response.

Below are a list of steps that will help diagnose the issue:
1. In “aws_iot_config.h” in the application example check that the connection settings (server endpoint, port) are the same as for your Beaglebone board.  
   The port should be 8883 the server endpoint for your account can be retrieved e.g. by using the AWS CLI “aws --region us-east-1 iot describe-endpoint”.
2. Please ensure that your Arduino board is connected to a WiFi network that has internet access and allows for traffic on TCP port 8883 (Secure MQTT).
3. Verify that the filenames for your credentials (rootCA, private key and certificate) match the files copied to the ones on the openWRT side to which they were copied following the setup instruction from readme. Ensure that those credentials are the same as for your Beaglebone board (which apparently works).
4. Ensure that you are using a unique ClientID for your Arduino Yun. Note that using the same client ID on multiple boards running with certificates for the same account at the same time will lead to disconnection of clients (per MQTT spec)
5. We are able to cause connectivity issues if OpenWRT is not fully booted up by the time the sketch is flashed. Make sure the board is fully booted up and connected to WiFi before uploading and running the sketch on Arduino. This can take up to 80 seconds.

In order to diagnose the issue further we kindly ask you to open a [support ticket](https://aws.amazon.com/contact-us/), to allow for exchange of account specific information.

Thanks,
The AWS Device SDK team

**Comment by Pillar1989** [comment]
I checked the filename. They are right. We didnt modify any source code. Just test the SDK.
Any way. If there are any runtime environment problem, The SDK  should print "setup failed".
and  "config failed".

**Comment by Pillar1989** [comment]
About 5, After we can ping http://wiki.com/,we test sdk. So there is no internet problem.

**Comment by liuszeng** [comment]
Hi @Pillar1989. Thank you for your response.

In order to further diagnose the issue, we need to take a look at your configuration files and the file list under /root/certs/ on openWRT. Please create customer support ticket and pass the values for the following variables into the ticket:

AWS_IOT_MQTT_HOST
AWS_IOT_MQTT_PORT
AWS_IOT_CLIENT_ID
AWS_IOT_MY_THING_NAME
AWS_IOT_ROOT_CA_FILENAME
AWS_IOT_CERTIFICATE_FILENAME
AWS_IOT_PRIVATE_KEY_FILENAME

Thanks,
The AWS Device SDK team

**Comment by Pillar1989** [comment]
@Jack1314  

## _Instructions_

In “AWS-IoT-Arduino-Yun-Library/examples/BasicPubSub/“:
In “aws_iot_config.h”, modify macro “AWS_IOT_CLIENT_ID” from “My_ClientID” to something else. For example:
#define AWS_IOT_CLIENT_ID “My_ClientID” —> #define AWS_IOT_CLIENT_ID “New Client ID”
2. Now re-flash the example sketch onto the board.
@liuszeng 
Thanks

**Comment by sean808080** [comment]
I had the issue that the second poster reported.  
Connect failed!
-5
Subscribe failed!
-7
Publish failed!

The resolution was to examine the AWS_IOT_ROOT_CA_FILENAME referenced in the aws_iot_config.h  It turns out that the file was actually a template that didn't contain the actual certificate.  After pasting in the cert body into the template, my connections worked.

**Comment by smartleoyu** [comment]
Hi,

I had this after uploading the sketch to the board:

AWS IoT SDK Version(dev) 1.0.2-

Setup failed!
-17

It does not even setup...

**Comment by liuszeng** [comment]
Hi @smartleoyu 

Thank you for trying out AWS IoT Arduino Yún SDK.

Error code -17 means that there is a communication error in Serial1 between Atmega and AR9331, which can be caused by the baud rate used for Serial1 communication. You can check the following things:
1. Verify the OS version of openWRT on your Arduino Board. To check that, you can ssh into OpenWRT and use command `uname -a`.
2. Verify Serial1 communication using Arduino Official example [YunSerialTerminal](https://www.arduino.cc/en/Tutorial/YunSerialTerminal). Check to see if this example is working for baud rate115200 and 250000. If it is working, you should be able to use the serial monitor as a terminal on OpenWRT.
3. Are you experiencing this error each time powering up the board or each time uploading the sketch?

It will be really helpful if we can gather these information.

Thanks,
The AWS Device SDK Team

**Comment by codehArt** [comment]
hello,
I am a newbie to aws iot,
and I am thinking about integration aws iot with an Arduino mkr1000 directly using any methods, so is it possible or not??,
 please help me.....

**Comment by Ganeshvadhri** [comment]
AWS_IOT: Error(-28) connecting to a1sc5ik8p3xc6d-ats.iot.us-east-1.amazonaws.com:8883,
