### ISSUE TITLE
Instructions to download the AWS IoT CA file does not match code assertion

### ISSUE THREAD

**Issue by millerbryan** [aws/aws-iot-device-sdk-arduino-yun#14]
The CA file downloaded as per the README.md file does not have the correct name to match the "credentialCheck" assertion in the ThermostatSimulatorApp.py example.

The Python code is looking for a file which matches this glob:

```
# Get credentials
rootCA = glob.glob("./certs/*CA.crt")
```

**Comment by liuszeng** [comment]
Hi @millerbryan ,

Thank you very much for your inputs on AWS IoT Arduino Yun SDK!

As is mentioned in the README.md:

> ... Please make sure to keep the file names as they are downloaded and make sure the CA file name ends with CA.crt.

You will need to download the rootCA file and give it a name that ends with "CA.crt" in order to be auto detected by the ThermostatSimulatorApp.py script.

We will update the example instructions to make it more intuitive in the upcoming release.

Thanks,
Liusu

**Comment by millerbryan** [comment]
Hi @liuszeng ,

The section you reference belongs in the "Installation" section.  I never found that section as I never made it that far.  I could not pass the "credentialCheck" assertion.

Thank you for all your work on the IoT service!
