### ISSUE TITLE
BasicPubSub: Connection Failed -13

### ISSUE THREAD

**Issue by shreyasrama** [aws/aws-iot-device-sdk-arduino-yun#20]
To try solve this I had a look at [this issue](https://github.com/aws/aws-iot-device-sdk-arduino-yun/issues/8) and also verified my file names were correct. After I SSH'd into the Arduino, my root CA (Symantec website one), IoT Certificate, and IoT private key (both generated through 1-Click certificate create in AWS IoT) were located in:

`/root/AWS-IoT-Python-Runtime/certs`

My `aws_iot_config.h` (which is on my local computer) has `AWS_IOT_PATH_PREFIX` set as `"../certs/"`, which is default. I tried changing file endings to match the format of the [original file](https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/AWS-IoT-Arduino-Yun-Library/examples/BasicPubSub/aws_iot_config.h) but that did not work.

Any ideas? Does the -13 error strictly mean it cannot locate the certs and key file? Thanks for the help.

**Comment by chaurah** [comment]
Hi @shreyasrama,
     I think the easiest thing to do here would be to ensure that the path that is being generated in the SDK is correct. You can go to [this](https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/AWS-IoT-Arduino-Yun-Library/examples/BasicPubSub/BasicPubSub.ino#L50) line in the code, and add a print statement to print out the path variables (AWS_IOT_ROOT_CA_PATH, AWS_IOT_PRIVATE_KEY_PATH, AWS_IOT_CERTIFICATE_PATH). That should let you confirm whether the full path is being generated correctly in the SDK. Can you please give this a try and let us know if that helps? Thank you for using AWS IoT.

Rahul

**Comment by shreyasrama** [comment]
Thanks for the quick response @chaurah . I can confirm after putting a Serial.println in there that all three path variables are pointing to `../certs/private-key.pem` or `../certs/certificate.crt`, etc. Therefore I changed the config so that the path variables were fully explicit e.g. `/root/AWS-IoT-Python-Runtime/certs/` however I still ran into the same error. I'm wondering if there are permission issues?

Also I assume when the .ino is loaded to the Yun the current working folder is `runtime`? Hence the `../certs/` being default.

**Comment by liuszeng** [comment]
Hi @shreyasrama ,

Thank you very much for using AWS IoT Arduino Yun SDK!

For the issue you are experiencing here, there are several things you can check:
1. Check the file name of all your credentials (certificate, private key and root CA) that you uploaded to the board AR9331 side. Make sure that they exactly match the name you put in the `aws_iot_config.h`. By default, the credentials you directly download from AWS IoT Console have the following format:
   
   <RANDOM_STRING>-certificate.pem.crt
   <RANDOM_STRING>-private.pem.key
   
   Make sure that you include all the parts of these file names. If you are modifying these file names, make sure that you also update them in the `aws_iot_config.h`.
2. If you are doing all the upload in Windows, there is chance where you might not be able to get the full file name with extensions on the host OS. After you upload the credentials to the board, simply do a `ls -al` under directory `/root/AWS-IoT-Python-Runtime/certs/` and check the full file names. You must specify the file names in the configuration to be exactly the same shown on the embedded Linux in order to make it recognizable for the SDK. Be careful about extensions ".pem.crt" and ".pem.key".
3. After you upload your credentials to the board, make sure you do a power cycle before you start running examples. Files that are newly uploaded might not be recognized immediately.

Please let use know how it goes.

Thanks,
Liusu

**Comment by shreyasrama** [comment]
Hi @liuszeng , @chaurah 

Checked all three steps, then redid the entire installation and I'm still having no luck. Here are the results of an `ls -al` after SSH to the Arduino:

![13707598_1223150991042652_2882031008292396649_n](https://cloud.githubusercontent.com/assets/8328647/16940788/3ca170d2-4de0-11e6-8f59-21853d2c40b8.jpg)

And the corresponding `aws_iot_config.h` that opens alongside BasicPubSub.ino in the IDE:

![13709828_1223151007709317_6948065035333489001_n](https://cloud.githubusercontent.com/assets/8328647/16940801/5178755a-4de0-11e6-95b7-1c9b0d31eaa6.jpg)
_edit: the picture is missing the second `/` on `../certs/`, it's been tested properly._

Is there an older version I could try? I came across this [StackOverflow question](http://stackoverflow.com/questions/36272307/unable-to-connect-aws-iot-to-arduino-yun-using-basic-pub-sub-example) and even tried putting them in the `/root/AWS-IoT-Python-Runtime/runtime/certs` folder like suggested, still didn't work.

Just an additional question, the MQTT broker created in the Yun is agnostic of what type of connection the Arduino has to the Internet correct? Like I'm using WiFi to try and get this demo working but I would ideally use a cellular connection via GPRS or GSM.

**Comment by liuszeng** [comment]
Hi @shreyasrama ,

Thank you very much for providing the detailed information!

In the configuration file, `AWS_IOT_MQTT_HOST` should be:

```
<RANDOM_STRING>.iot.us-west-2.amazonaws.com
```

The https one is the one for REST APIs. You can find your MQTT endpoint by clicking the question mark on the top-right in you AWS IoT Console.  
![image](https://cloud.githubusercontent.com/assets/14796906/16960017/87d8021c-4d9c-11e6-98d6-938052f66fe0.png)

And you should be able to see you AWS IoT MQTT endpoint:  
![image](https://cloud.githubusercontent.com/assets/14796906/16960116/f31781f6-4d9c-11e6-82e7-fd907e999f44.png)

We will try to fix the SDK error code to be more specific.

As for the additional question, Yun SDK is agnostic of what type of connection the Arduino has to the internet. Note that the SDK is for Arduino Yun compatible boards and is built on top of the dual-processor architecture. It runs a Python runtime on the AR9331. The embedded Linux provides internet access through WiFi. You will need to configure the embedded Linux to use cellular connection.

As a side note, Yun SDK supports MQTT over WebSocket since v1.1.0. You can also use IAM credentials for authentication if you find it hard to manipulate with certificates.

Thanks,
Liusu

**Comment by shreyasrama** [comment]
Oops. Everything works now :+1: sorry about that.

Just before you close the issue, my idea was to use a GPRS shield for the cellular connection, I suppose it's not sufficient enough to set up a GPRS connection in the setup area of the Arduino code? I would still need to tell the embedded Linux to use GPRS?

Thanks for all the help.

**Comment by liuszeng** [comment]
Hi @shreyasrama ,

Glad to know that it is working for you!

As for using cellular connection on an Arduino Yun, cellular connection on an Arduino board often comes through a GPRS shield which talks AT command. I would assume it jumps over the embedded Linux and directly talks to the hardware. Since Arduino Yun SDK is built on top of the serial communication between Atmega 32u4 and AR9331. All the heavy lifting, including internet connections, are on embedded Linux. You will need to explicitly configure the embedded Linux to use the GPRS shield for internet connection.

Follow the guide of your GPRS shield and see if you can control it on the embedded Linux side. Another assumption I have is that you might need to talk over the serial bridge/software serial in order to communicate with your GPRS shield from embedded Linux. Make sure that the communication channels are not overlapping with each other since the SDK is using hardware serial1 port.

Sorry that I cannot provide a more positive answer right now but hope the above could at least give you a hint on how you can proceed. Please feel free to open another thread if you have more questions.

Thanks,
Liusu

**Comment by mohdrashid** [comment]
Hi There, I followed the tutorial, Everything works. However when it comes to connect it fails by giving error -1 .

Connect failed!
-1

Any idea why this is happening?
