### ISSUE TITLE
Serial1 error on re-upload

### ISSUE THREAD

**Issue by jochasinga** [aws/aws-iot-device-sdk-arduino-yun#23]
I kept getting SERIAL1_COMMUNICATION_ERROR (-5) on re-upload. Always had to reset the Yun over again. 

``` arduino

void setup() {

    Serial.begin(115200);
    while(!Serial);

    if ((rc = myClient.setup(AWS_IOT_CLIENT_ID)) == 0) {
        Serial.println(F("Begin setup..."));

        // ... 
    } else {

        // This two lines print out rc = -5
        Serial.println(F("Setup failed"));
        Serial.println(rc);
    }

```

**Comment by chaurah** [comment]
Hi @jochasinga,
     Can you please provide some more information about the code you are running? Are you running one of the samples or is it custom code? And if it is custom code, have you tried running and re-uploading with the sample code?

Rahul

**Comment by jochasinga** [comment]
It seems like publishing to MQTT (and failed with -17) created the issue.

``` arduino

void loop() {
    if(success_connect) {
        // This line failed with -17 and make re-uploading failed with -5 afterward.
        myClient.publish("topic1", "myMessage", 1, strlen("myMessage"), false));
        if(myClient.yield()) {
            Serial.println(F("Yield failed."));
        }    
        delay(1000); // check for incoming delta per 100 ms
    }
}

```

@chaurah can you recreate that?

**Comment by liuszeng** [comment]
Hi @jochasinga ,

Thank you very much for your interest in AWS IoT Arduino Yun SDK!

To get more debug information from the AR9331 side, could you please add a serial.println(...) after this line: https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/AWS-IoT-Arduino-Yun-Library/aws_iot_mqtt.cpp#L851  to print out the rw_buf when you are experiencing the issue (PUBLISH_GENERIC_ERROR -17) ?

Thanks,
Liusu

**Comment by jochasinga** [comment]
Below is the log file:

``` shell

rw_buf:
rw_buf:t@Arduino:~/AWS-IoT-Python-Runtime/runtime# 1
rw_buf:/bin/ash: /root: Permission denied
rw_buf:/bin/ash: 1: not found
rw_buf:/bin/ash: /root: Permission denied
rw_buf:/bin/ash: 1: not found
rw_buf:/bin/ash: /root: Permission denied
rw_buf:/bin/ash: 1: not found
rw_buf:/bin/ash: /root: Permission denied
rw_buf:Linux
rw_buf:/
rw_buf:
rw_buf:
rw_buf:
rw_buf:
rw_buf:
rw_buf:
rw_buf:I T
[LOG] command: setup completed.
rw_buf:
rw_buf:
rw_buf:
rw_buf:
rw_buf:
rw_buf:
rw_buf:G T
[LOG] command: config completed.
rw_buf:
rw_buf:
rw_buf:C T
[LOG] command: connect completed.
rw_buf:
rw_buf:
rw_buf:
rw_buf:
rw_buf:S T
[LOG] command: subscription completed.
rw_buf:
rw_buf:
rw_buf:
rw_buf:SI T
[LOG] command: shadow init completed.
rw_buf:
rw_buf:
rw_buf:
rw_buf:S_RD T
[LOG] command: register thing shadow delta function completed.
rw_buf:
rw_buf:
rw_buf:
rw_buf:
rw_buf:
rw_buf:PFF: Unknown error.
[ERR] command: publish code: -17
rw_buf:
rw_buf:Z T
rw_buf:
rw_buf:Y F: No messages.
rw_buf:
rw_buf:
rw_buf:
rw_buf:
rw_buf:
rw_buf:
[ERR] command: publish code: -1
rw_buf:
rw_buf:
Yield failed.
rw_buf:
rw_buf:
rw_buf:
rw_buf:
rw_buf:

```

**Comment by liuszeng** [comment]
Hi @jochasinga ,

Can you make changes to:
https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/AWS-IoT-Python-Runtime/lib/command/commandPublish.py#L58
to expose the error message?

```
...
returnMessage = "PFF: " + str(e.message)
...
```

Also, are you running one of the SDK samples? Can also you include your memory consumption stats (the amount of SRAM memory used)? Is there any error message shown in the Arduino IDE when you compile the sketch?

Thanks,
Liusu

**Comment by jochasinga** [comment]
@liuszeng please reopen this issue. It hasn't been resolved.

I just had the time to dig into the code and found that this `SERIAL1_COMMUNICATION_ERROR` (-5) error is returned here https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/39e62018770f49bcb92451ea7a83faf95c753aa8/AWS-IoT-Arduino-Yun-Library/aws_iot_mqtt.cpp#L99-L101 due to `BAUD_TYPE_UNKNOWN` returned when `find_baud_type()` is called and nothing to do with publishing message at all.

However, when I force-replaced the `baud_type` to `BAUD_TYPE_LININO` or `BAUD_TYPE_ARDUINO`, `GENERIC_ERROR` (-1) was returned at setup instead of -5. This brought me to this block https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/39e62018770f49bcb92451ea7a83faf95c753aa8/AWS-IoT-Arduino-Yun-Library/aws_iot_mqtt.cpp#L85-L88 in `setup_exec()` but I wasn't good enough in C++ to see this through without further research.

To answer your previous question, I ran a heavily modified example which can be found [here](https://github.com/jochasinga/yun-gps-iot) and the memory usage was normal:

```
Sketch uses 15,970 bytes (55%) of program storage space. Maximum is 28,672 bytes.
Global variables use 1,465 bytes (57%) of dynamic memory, leaving 1,095 bytes for local variables. Maximum is 2,560 bytes.
```

This issue has emerged several times that I think it's important and should be fixed.

**Comment by liuszeng** [comment]
Hi @jochasinga ,

Thank you for providing the information.

The issue is caused by this line:
https://github.com/jochasinga/yun-gps-iot/blob/master/BasicPubSub.ino#L68

Unfortunately, the current version of AWS IoT Arduino Yun SDK and Bridge library functionality cannot be used at the same time.

The AWS IoT Arduino Yun SDK is built on top of the dual-processor-architecture, with ATmega32u4 and AR9331. In order to make it possible for the board to connect to AWS IoT, a Python runtime is implemented on the OpenWRT side to let the more powerful chip do the heavy-lifting work (with more memory and more libraries for secured MQTT). Communication messages are transmitted over Serial1 connection to perform a request/response interaction.
https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/AWS-IoT-Arduino-Yun-Library/aws_iot_mqtt.cpp#L63

The Bridge library shares the same implementation behind the scene. It also uses the Serial1 channel to transmit sketch commands and retrieve output from the Linux. 
https://github.com/arduino-libraries/Bridge/blob/master/src/Bridge.cpp#L54

Since Bridge library is sharing the same communication channel with the SDK, using them at the same time will break the protocol in between.

Related issue: https://github.com/aws/aws-iot-device-sdk-arduino-yun/issues/7

A possible workaround here is to add a custom command into the SDK Python runtime that performs your desired Linux command and an extra API in the SDK C++ library to start the request/receive the response, just like the MQTT commands included:
Connect (C++ API):
https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/AWS-IoT-Arduino-Yun-Library/aws_iot_mqtt.cpp#L232
Connect (Python runtime API):
https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/AWS-IoT-Python-Runtime/lib/command/commandConnect.py

Thanks,
Liusu

**Comment by jochasinga** [comment]
@liuszeng thanks I'll take a jab at it.

**Comment by dsandi** [comment]
I don't understand why you have examples on the arduino yun sdk that cannot run on the arduino yun.  

I cannot run the [most basic example](https://github.com/aws/aws-iot-device-sdk-arduino-yun/tree/master/AWS-IoT-Arduino-Yun-Library/examples/BasicPubSub) because I get the same error.

**Comment by liuszeng** [comment]
Hi @dsandi ,

I am sorry that the SDK sample is not working for you.

Can you describe more about the error you are seeing here? Can you include some logging output from the Serial monitor when you are running the sample?

Also, note that this is a closed issue. Please feel free to start a new thread if that is applicable.

Thanks,
Liusu

**Comment by dsandi** [comment]
I started https://github.com/aws/aws-iot-device-sdk-arduino-yun/issues/39 Thank you!
