### ISSUE TITLE
Getting a date value without using process date process.h

### ISSUE THREAD

**Issue by OtisHarrison24** [aws/aws-iot-device-sdk-arduino-yun#40]
Is there anyway to get a timestamp to pass from the aws iot sdk to pass into my json file?

Thanks

**Comment by liuszeng** [comment]
Hi @OtisHarrison24 ,

Thank you very much for your interest in AWS IoT Arduino Yun SDK.

If you are looking for getting the timestamp from Arduino board instead of the embedded Linux, you can try out the following library:
http://playground.arduino.cc/Code/Time

`now()` should give you a timestamp in seconds since Jan. 1, 1970.

Thanks,
Liusu
