### ISSUE TITLE
ThermostatSimulator device 

### ISSUE THREAD

**Issue by escissorshand** [aws/aws-iot-device-sdk-arduino-yun#44]
HI, i have problem running the ThermoStatSimulator.py. it provides an invalid syntax error on line 7.

image
![image](https://cloud.githubusercontent.com/assets/24651418/25170342/cc7ef828-251c-11e7-83a7-03058246a0e1.png)

And on my serial monitor the setup monitor just hang on the following.

image
![image](https://cloud.githubusercontent.com/assets/24651418/25170345/d1db6662-251c-11e7-9443-d72bcf21dcad.png)

However, i have shadow updates on the AWS IOT console. i believe the connection to the AWS IOT console is successful.

image
![image](https://cloud.githubusercontent.com/assets/24651418/25170354/d9bdd9e6-251c-11e7-8c08-d6944e6bd9a2.png)

thanks in advance for your help.

**Comment by liuszeng** [comment]
Hi @escissorshand ,

Thank you very much for your interest in AWS IoT Python SDK.

It seems that there is a line of `<!DOCTYPE html>` at the beginning of your `ThermostatSimulatorApp.py`. Can you open the file and check it again? You should be able to find the script in the SDK repo here:
https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/ExampleAppScript/ThermostatSimulatorApp/ThermostatSimulatorApp.py

One other thing worth mentioning here is, the application script is operation on the device shadow with a fixed name `room`. See details here:
https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/ExampleAppScript/ThermostatSimulatorApp/ThermostatSimulatorApp.py#L154

To get the application script working with the Arduino Yun sketch, you want to keep the device shadow name same so that they can interacting with each other via the same shadow. For more details about the sample, you can check out the documentation here:
https://github.com/aws/aws-iot-device-sdk-arduino-yun#simple-thermostat-simulator

Thanks,
Liusu

**Comment by escissorshand** [comment]
thanks Liusu,


I can now launch the ThermostatSimulatorApp.py application. 

However, when i launch the Arduino IDE serial monitor there is no print logs. but i know its at the void (loop) function through some serialprint statement.

![image](https://cloud.githubusercontent.com/assets/24651418/25265935/e4b08b4c-26a1-11e7-96f6-c3b81cdef41a.png)

the data is also being updated on the shadow on the AWS IOT 

![image](https://cloud.githubusercontent.com/assets/24651418/25266058/5a5491e0-26a2-11e7-9bff-d78c7ee92460.png)


the reported temperature is also not capture on the ThermostatSimulatorApp.py application. 

![image](https://cloud.githubusercontent.com/assets/24651418/25266158/c069e584-26a2-11e7-91cf-8b8cdb43b906.png)


how do i keep the device shadow name same?

_To get the application script working with the Arduino Yun sketch, you want to keep the device shadow name same so that they can interacting with each other via the same shadow. For more details about the sample, you can check out the documentation here:_

**Comment by escissorshand** [comment]
I think the device shadow name is change under the aws_iot_config file 
#define AWS_IOT_MY_THING_NAME "room"	

After changing that. it works.

![image](https://cloud.githubusercontent.com/assets/24651418/25267035/f20dcc56-26a5-11e7-9e91-f68f481792f4.png)
