### ISSUE TITLE
Keep getting "Out of buffer size" during callback for shadow_get

### ISSUE THREAD

**Issue by silverfangs** [aws/aws-iot-device-sdk-arduino-yun#5]
Guys, I keep getting "Out of buffer size" during callback for myClient.shadow_get("xxxx", myCallback, 5);

Im not sure whether I putting it wrong for my callback function as shown below:

```
void myCallback(char* src, int len) {
    String data = String(src);
    Serial.println(data);
}
```

**Comment by silverfangs** [comment]
My mistake, my last update to the state my device wrongly, causing it too big in size, that's why keep getting "Out of buffer size" when callback.

**Comment by liuszeng** [comment]
Hi @silverfangs ,

Thank you for trying out AWS IoT Arduino Yun SDK!

Usually, when you are doing a shadow get, the message that comes back contains metadata for each attribute of the shadow state. "OUT OF BUFFER SIZE" means that the local message buffer space on Arduino Yun Atmega is not enough to hold the incoming message from IoT. It is configurable in `libraries/AWS-IoT-Arduino-Yun-Library/aws_iot_config_SDK.h`, the default size is set to 256 bytes:

```
#define MAX_BUF_SIZE 256
```

This is the macro that defines the maximum number of bytes to publish/receive for a single message. An increase of 1 byte results in 2 bytes of memory consumption in Atmega SRAM since it is for both publish and receive.

You can change it to make a larger buffer but keep in mind that the SRAM space on Atmega is limited and please make sure that you are not using too much of the space for the buffer. High percentage of SRAM usage could result in unstable behaviors on Arduino Yun.

Thanks,
AWS IoT Device SDK Team
