### ISSUE TITLE
SDK Interference with Bridge Library's Process

### ISSUE THREAD

**Issue by andrewvaslas** [aws/aws-iot-device-sdk-arduino-yun#7]
I am attempting to build a gateway with the Yun (my LAN on one end, AWS IoT on the other). Specifically, I have a set of Philips Hue bulbs, the state of which I'd like to keep in Device Shadows. (Also, remote control would be awesome.)

I have set up the SDK on my Yun and successfully connected, set up the Shadow, updated it, and registered my delta function callback. However, when I try to integrate this with Philips Hue control, it breaks.

My Hue communication code:

```
void setup() {
  // Initialize Bridge
  Bridge.begin();

  // Initialize Serial
  Serial.begin(9600);

  // Wait until a Serial Monitor is connected.
  while (!Serial);

  // Authenticate with Hue bridge (uncomment this if connecting to bridge for first time).
  //authenticate();

  // Turn lights on
  runCurl(true);
}

/*
 * Launches "curl" command and sends state to lights
 */
void runCurl(boolean on) {
  // Create process over Yun's bridge
  Process p;
  // Launch curl command
  p.begin("curl"); 
  String s1 = String(" -d ");
  String quote = String('"');

  // Set payload
  String payload;
  if (on) {
    if (isOn) {
      // Update color with transition time
      payload = String("{\"hue\":" + String(hue) + ",\"bri\":" + String(sat) +  ",\"transitiontime\":" + String(50) + "}");
    }
    else {
      // Turn light on
      payload = String("{\"on\":true,\"hue\":" + String(hue) + ",\"bri\":" + String(sat) + "}");
    }
  }
  else {
    // Turn light off
    payload = String("{\"on\":false,\"hue\":" + String(hue) + ",\"bri\":" + String(sat) + "}");
  }

  // Set new state
  isOn = on;

  // Build request
  String url = String("http:/");
  String url2 = String("/" + BRIDGE_IP + "/api/19aa6134f32d16f3fa3e75cdc0ed7/groups/0/action");
  String params = s1 + quote + payload + quote  + url + url2;
  p.addParameter("-d");
  p.addParameter(payload);
  p.addParameter("-X");
  p.addParameter("PUT");
  p.addParameter(url + url2);

  // Run the process and synchronously wait for its terimination
  p.run();

  // Read process output stream; uncomment to print stream over serial
  while (p.available()>0) {
    char c = p.read();
//    Serial.print(c);
  }

  // Ensure the last bit of data is sent
  Serial.flush();
}
```

It seems that both the Hue communication and the AWS IoT SDK require access to the Bridge in such a way that they cannot coexist. Is this correct? If so, is there any way to send a web request (using a CURL Process or not) while the SDK is running? If not, this would be a huge bummer....

**Comment by liuszeng** [comment]
Hi andrewvaslas@, 

Thank you very much for your interest in AWS IoT Arduino Yun SDK. 

Unfortunately, the current version of AWS IoT Arduino Yun SDK and Bridge library functionality cannot be used at the same time.

The AWS IoT Arduino Yun SDK is built on top of the two-processor-architecture, with ATmega32u4 and AR9331, the one with the embedded Linux OpenWRT running on it. In order to make it possible for the board to connect to AWS IoT, a Python runtime is implemented on the OpenWRT side to let the more powerful chip do the heavy-lifting work (with more memory and more libraries for secured MQTT).

The Bridge library comes with a series of built-in functionalities that make it possible to perform operations on OpenWRT with commands sent from ATmega sketch. This is completed using Serial1 communication behind the scene. However, it does not expose low-level socket or ssl module that can be utilized for secured MQTT (TLS+MQTT). Therefore we decide to create the runtime on OpenWRT individually and also create the Serial1 communication that handles request/response between the two chips specifically for AWS IoT. 

By now, Bridge library cannot be used at the same time with the AWS IoT Arduino Yun SDK since they share the same channel, Serial1, for communication. It might be possible in the future to include the SDK code into the Bridge library so that their functionalities can coexist, but that requires modification on native Arduino Yun libraries.

We are sorry for not being able to provide a more positive answer at the moment and we will continue to look into this.

Thanks, 
Liusu

**Comment by vaneek** [comment]
Hi @andrewvaslas,

One possibility may be to use the SDK for Node.js on the OpenWRT side and your code on the ATmega side. This may require some additional coding but it would free up the serial channel for the bridge code.

I haven't tried this(yet) myself and it may introduce other problems as well but maybe others can provide some insight on this.

**Comment by mondragonsi** [comment]
Can Guys, I am using Arduino Uno with yun shiled (dragino). Do you know if I can use Serial instead of Serial1? Thanks!
